version: '3'

services:
  django_gunicorn:
    volumes:
      - static:/static
      - media:/app/media
    env_file: 
      - .env
    build:
      context: .
    ports: 
      - "8000:8000"
  frontend:
    restart: unless-stopped
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: canelosspa56@gmail.com
    volumes:
       - static:/static
       - media:/app/media
       - ./conf.d:/etc/nginx/user.conf.d:ro
       - letsencrypt:/etc/letsencrypt      
    depends_on:
      - django_gunicorn
volumes:
  media:
  static:
  letsencrypt:
